### ISSUE TITLE
Fullscreen and alt issues

### ISSUE THREAD

**Issue by Zabooby** [Astromations/FlyingFox#10]
- The window controls stay visible
- Would it be possible to get the same animations as the sidebar and bookmarks bar when autohiding the navbar? 
- Pressing alt, causes a small delay when window controls reposition

https://github.com/Astromations/FlyingFox/assets/78969986/8bb7fed1-6e15-4583-b638-99e147950be7

**Comment by Astromations** [comment]
Hey! Just pushed a bunch of commits that should fix all of this. If you get a moment, download it and let me know if they work. I don't wanna close the issue until I'm sure.

**Comment by Zabooby** [comment]
Wow great work, all the issues are now fixed!

I'm not sure if you missed my comment in the other issue but could you remove the padding on the left side in the history sidebar for better readability? 
![image](https://github.com/Astromations/FlyingFox/assets/78969986/41fb745f-44b8-4e6c-9f26-4e34cc353cbf)

Would it be possible to also apply animations when pressing alt? 

Also how would I reduce the padding for tabs in a tree?
![image](https://github.com/Astromations/FlyingFox/assets/78969986/fa5746dd-da43-4cc7-980e-0d2a3bd57d61)

Would you be interested in adding your fork to the [Firefox css store](https://firefoxcss-store.github.io/), I know the original is already on there but maybe you could ask to replace it with yours, it would be great to have more people try out FlyingFox again? 

Other than that everything is now running smoothly for me, thanks for maintaining this great theme!

**Comment by Astromations** [comment]
Well the spacing is actually supposed to be there cause of the way the label moves. If you wanna remove it go to  about line 130 of treestyletabs.css, add this 

```
tab-item .twisty {
  display: none
}
```
and change the padding for the label selector right above it. It's 8px by default. Should look something like this:
![image](https://github.com/Astromations/FlyingFox/assets/80211195/485b54fc-f528-445a-b2cd-a92d665ddb31)

Working on a fix for the history bar rn, but that spacing is supposed to be there. It'd look weird if it hugged the left side.

Haven't thought about adding it to css store. I'll definitely look into how to do that.

**Comment by Astromations** [comment]
To fix the history bar add this line to `interface.css` under `#historyTree`. Tweak the padding property as you you please.
`margin-left: -8px !important;`
Should look like this
![image](https://github.com/Astromations/FlyingFox/assets/80211195/7f3e4d1b-4b71-4680-9c61-cada37bdcfe7)

**Comment by Zabooby** [comment]
I've tried tweaking the margin-left value but no number seems to have any effect?
![image](https://github.com/Astromations/FlyingFox/assets/78969986/5af79abf-ab6a-47db-bb0f-55a5c747a6e7)

**Comment by Astromations** [comment]
My bad! That's the wrong selector. Add this and all should be well:
```
#historyTree {
  margin-left: -8px !important
}
```
Sorry the fix took so long. I've been finishing up my exams.

**Comment by Zabooby** [comment]
Thanks it works perfectly. 

I think you missed my reply in #8, I understand why you don't plan to fix this, but what files would I have to change to tweak it (my ocd will be the death of me)?

**Comment by Astromations** [comment]
My bad! Forgot. Throw this in `interface.css` and the extra padding should be gone. 
```
.toolbarbutton-badge {
	padding: 0 2px 0px !important;
}
```

**Comment by Zabooby** [comment]
Closed
