### ISSUE TITLE
Auto hiding the bookmarks bar is broken in v117.0

### ISSUE THREAD

**Issue by Zabooby** [Astromations/FlyingFox#14]
The bookmarks bar no longer shows when hovered over it.

**Comment by bphd** [comment]
Why closing

**Comment by Zabooby** [comment]
fixed it: https://github.com/Zabooby/firefox-config

**Comment by bphd** [comment]
You should upstream. It's not only about scratching your own itch, but about noticing a problem upstream and working on it for the solution to become better

**Comment by Zabooby** [comment]
Totally agree, I've actually made the only pr on this repo. But I created my own because this one seems to be dead in the water unfortunately.

**Comment by bphd** [comment]
> Totally agree, I've actually made the only pr on this repo. But I created my own because this one seems to be dead in the water unfortunately.

No grief, you did what was right
