### ISSUE TITLE
Firefox 119 broken parts of the theme

### ISSUE THREAD

**Issue by L-Ratio** [Astromations/FlyingFox#16]
**Describe the bug**
The urlbar colors not being applied and the windows mac-os buttons are incorrectly colored
**To Reproduce**
1. Download the theme
2. boom

**Screenshots**
![image](https://github.com/Astromations/FlyingFox/assets/54047268/d36705b2-9dd5-4a90-b893-fa40b148dd64)

 **Firefox Version:**
119

**Steps taken**
Redownloaded the theme.
Turned dark mode on.

**Comment by bphd** [comment]
Why closing
