### ISSUE TITLE
Improve usability of bookmarks and history sidebars

### ISSUE THREAD

**Issue by Zabooby** [Astromations/FlyingFox#2]
![image](https://user-images.githubusercontent.com/78969986/236788155-9a4f2a98-7be9-4e93-829e-a048a8e95aca.png)

To improve usability, make it so that the sidebar only autohides when TST is active, this is already the case for bookmarks sidebar but not the history sidebar shown above. 

Have the same functionality with sidebar headers  (only autohide when TST is active) so users can quickly switch back to TST. 

And finally match the bookmarks and history sidebar colours with the rest of the FlyingFox colours.

**Comment by Astromations** [comment]
I've been busy as of late. When I get some time on my hands I'll see what I can do.

**Comment by Astromations** [comment]
Done. If there's anything else about the sidebar you think needs changing, open a new issue and I'll see what I can do.

**Comment by Zabooby** [comment]
Works great, but could you also remove the extra padding on the left side?

![image](https://github.com/Astromations/FlyingFox/assets/78969986/41fb745f-44b8-4e6c-9f26-4e34cc353cbf)
