### ISSUE TITLE
Tooltips on ui buttons don't follow theme

### ISSUE THREAD

**Issue by Zabooby** [Astromations/FlyingFox#3]
Tooltips on websites all follow the themes colours but tooltips for some Firefox buttons don't. 

![image](https://user-images.githubusercontent.com/78969986/236486078-50a6ee92-0556-4cd2-ba88-ffcffb89cead.png)

**Comment by Astromations** [comment]
I've been trying to fix this and frankly, I'm stumped. This is out of my range of expertise. If you know any other themes that manage to change the Home and Extension tooltips please tell me. For now, no development on this front.

**Comment by Zabooby** [comment]
My exams finish on Tuesday, I'll check some of the more comprehensive themes that I know then. I'll also open issues for the other bugs I've found too. 

If you want you could try asking in the r/firefoxcss subreddit or on matrix (link in the subreddit sidebar), iirc there is a dev channel that could help.

**Comment by Zabooby** [comment]
Ok after testing a bunch of other themes, including these:
https://github.com/BloodyHell619/Firefox-Theme-DarkMatter
https://github.com/aminomancer/uc.css.js#installation

as well as some googling I'm pretty sure these tooltips can't be customised, should I close this issue?

**Comment by Astromations** [comment]
I'll close it dw.

**Comment by Zabooby** [comment]
@Astromations I found a solution, it needs to be done with js. 

See [these rules](https://github.com/aminomancer/uc.css.js/blob/master/userChrome.ag.css#L17-L45). Stylesheet must be loaded as an [agent sheet](https://github.com/aminomancer/uc.css.js#agentauthor-sheet-loader).

PS: Did you find a way to have smooth animations when pressing alt? 
PPS: This css doesn't seem to have any effect (#10)?
```
.toolbarbutton-badge {
	padding: 0 2px 0px !important;
}
```
