### ISSUE TITLE
Scrollbar flashes when using right click menu

### ISSUE THREAD

**Issue by Zabooby** [Astromations/FlyingFox#5]
While testing v113.0 compatibility, I noticed the scrollbar flashes when using right click menu. This is after changing any incompatiable -mox-box css. 

https://github.com/Astromations/FlyingFox/assets/78969986/f8165d9c-ddf5-43d1-9c05-ba90f62f7819

**Comment by Astromations** [comment]
How have I not noticed that? I'll see what I can do. Exams are taking a lot of my time so updates and fixes might be slow for a little while.

**Comment by Zabooby** [comment]
No worries, I have exams coming up too. I've kept a a list of minor issues that I've come across, but I'll add them once we both get time to get through these issues first.
