### ISSUE TITLE
Sidebar without the correct format / Windows control on the wrong side

### ISSUE THREAD

**Issue by boterocamilo** [Astromations/FlyingFox#7]
**Bugs**

1. Windows controls are wrong. I'm using MacOS, so it should be on the left and not the right side.
2. The sidebar does not look like yours; as you can see in the video, it does not show the information correctly when hidden and does not have the same style.

**Video**

https://github.com/Astromations/FlyingFox/assets/46091241/a1f47029-516a-419e-98af-30309e9017e6

 **Firefox Version:**
113.0.2 (64-bit)

**Comment by Zabooby** [comment]
Have you added the [style settings](https://github.com/Astromations/FlyingFox/tree/master/treestyletab) in the tst settings?
![image](https://github.com/Astromations/FlyingFox/assets/78969986/37c8d2ed-4cfd-4ea0-9f32-21f438fbe67d)
