### ISSUE TITLE
The uBlock Origin counter is misaligned 

### ISSUE THREAD

**Issue by Zabooby** [Astromations/FlyingFox#8]
The blocked counter is too far to the right for 3 digit numbers:
![image](https://github.com/Astromations/FlyingFox/assets/78969986/7a709219-d471-4433-b4d2-9bc1a389d154)
![image](https://github.com/Astromations/FlyingFox/assets/78969986/90746d5a-b7aa-4a8c-8dfb-7d82a323fb33)

Also I might be crazy but are digits a few pixels too high too? 
![image](https://github.com/Astromations/FlyingFox/assets/78969986/4de1e6d9-12e9-4287-9e13-d61005c80c90)

**Comment by Astromations** [comment]
You have quite the eye for detail. It's not supposed to be middle aligned for 3 digits. It's always in the top right, the 3 digits just make it look misaligned cause its wider. As for the vertical misalignment, its a pixel of padding for readability.

**Comment by Zabooby** [comment]
Makes sense, but to calm my chronic ocd which files would I need to change to centre 3 digit numbers?
