### ISSUE TITLE
Icons on far left of url bar hover backgrounds cutoff

### ISSUE THREAD

**Issue by Zabooby** [Astromations/FlyingFox#9]
![image](https://github.com/Astromations/FlyingFox/assets/78969986/f71d8486-8206-40dc-8c99-71d4bb2f45ce)
![image](https://github.com/Astromations/FlyingFox/assets/78969986/fd57f557-548e-4176-a5cf-55211a86ccf8)

How hover background should look:
![image](https://github.com/Astromations/FlyingFox/assets/78969986/e754cdb8-a843-4292-8cef-ea06e108a9f5)

**Comment by Astromations** [comment]
Fixed
